# NumPy Student Workbook

Questions only. Write answers in the empty code cells below each question.

Q1. Create a NumPy array containing 10, 20, 30, 40, 50.

In [25]:
import numpy as np 
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


Q2. Create numbers from 1 to 20.

In [26]:
a=np.arange(1,21,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q3. Create even numbers from 2 to 20.

In [27]:
a=np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


Q4. Create a 3×4 matrix of zeros.

In [28]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Q5. Create a 4×3 matrix of ones.

In [29]:
print(np.eye((3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q6. Generate 10 evenly spaced values between 0 and 1.

In [30]:
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q7. Create a 2×3 array and find shape, ndim and dtype.

In [31]:
a=np.array([[1,2],[4,5],[7,8]])
print(a.shape)
print(a.ndim)
print(a.dtype)

(3, 2)
2
int64


Q8. Create a 4×5 array and find shape, size and ndim.

In [32]:
a = np.arange(20).reshape(4, 5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Q9. Convert [1,2,3,4,5] to float datatype.

In [33]:
a=np.array([1,2,3,4,5])
b=[float(x) for x in a ]
print (b)

[1.0, 2.0, 3.0, 4.0, 5.0]


Q10. Create numbers 1–12 and reshape into 3×4, 2×6 and 4×3.

In [34]:
print(np.arange(1, 13, 1).reshape(3, 4))
print(np.arange(1, 13, 1).reshape(2, 6))
print(np.arange(1, 13, 1).reshape(4, 3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q11. Create np.arange(20) and reshape into 4×5 and 5×4.

In [35]:
print(np.arange(1,21,1).reshape(4,5))
print(np.arange(1,21,1).reshape(5,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


Q12. Explain why np.arange(10).reshape(3,4) produces an error.

np.arange(10).reshape(3,4) gives an error because 10 elements cannot be reshaped into a 3*4 array, which requires 12 elements.

Q13. Using a 4×4 array, extract the first element.

In [36]:
a=np.arange(1,17,1).reshape(4,4)
print(a)
print(a[0,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1


Q14. Extract the value 10 from a 4×4 array created using arange.

In [37]:
a=np.arange(1,17,1).reshape(4,4)
print(a[2,1])

10


Q15. Extract the last element.

In [38]:
a=np.arange(1,17,1).reshape(4,4)
print(a[3,3])

16


Q16. Extract the first row.

In [39]:
a=np.arange(1,17,1).reshape(4,4)
print(a[0])

[1 2 3 4]


Q17. Extract the third row.

In [40]:
a=np.arange(1,17,1).reshape(4,4)
print(a[2])

[ 9 10 11 12]


Q18. Extract the second column.

In [41]:
a=np.arange(1,17,1).reshape(4,4)
print(a[:,1])

[ 2  6 10 14]


Q19. Extract the last column.

In [42]:
print(a[:,3])

[ 4  8 12 16]


Q20. Extract first two rows.

In [43]:
print(a[0:2])

[[1 2 3 4]
 [5 6 7 8]]


Q21. Extract last two rows.

In [44]:
print(a[2:4])

[[ 9 10 11 12]
 [13 14 15 16]]


Q22. Extract first three columns.

In [45]:
print(a[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


Q23. Extract last two columns.

In [46]:
print(a[:,2:4])

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


Q24. Extract a 2×2 center block.

In [47]:
print(a[1:3,1:3])

[[ 6  7]
 [10 11]]


Q25. Extract bottom-right 3×3 block.

In [48]:
print(a[1:4,1:4])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


Q26. Extract center element.

In [49]:
d=np.arange(9).reshape(3,3)
print(d)
print(d[1,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


Q27. Extract center 3×3 block.

In [50]:
e=np.arange(1,26,1).reshape(5,5)
print(e[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Q28. Extract top-right corner block.

In [51]:
print(a[0:3,1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


Q29. Extract bottom-left corner block.

In [52]:
print(a[1:4,1:4])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


Q30. Extract the main diagonal manually using slicing/indexing.

In [53]:
import numpy as np
a=np.arange(1,17,1).reshape(4,4)

print(a[[0,1,2,3],[0,1,2,3]])

[ 1  6 11 16]


Q31. Extract every alternate row.

In [54]:
print(a[0:4:2,:])

[[ 1  2  3  4]
 [ 9 10 11 12]]


Q32. Extract every alternate column.

In [55]:
print(a[:,0:4:2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


Q33. Reverse the rows.

In [56]:
print(a[::-1,:])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Q34. Reverse the columns.

In [57]:
print(a[:,::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


Q35. Reverse the entire matrix.

In [58]:
b = a[::-1,::-1]
print(b)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Q36. Extract a 3×3 reversed center block.

In [59]:
print(b[1:4,1:4])

[[11 10  9]
 [ 7  6  5]
 [ 3  2  1]]


Q37. Extract only the corner elements.

In [60]:
print(b[[0,0,3,3],[0,3,0,3]])

[16 13  4  1]


Q38. Extract only the border elements.

In [61]:
print(b[[]])

[]


Q39. Increase sales [100,200,300,400] by 10.

In [62]:
c=np.array([100,200,300,400])
print(c+10)

[110 210 310 410]


Q40. Increase salaries by 15%.

In [63]:
print(c*(15/100)+c)

[115. 230. 345. 460.]


Q41. Apply 18% GST to prices.

In [64]:
print(c*(18/100)+c)

[118. 236. 354. 472.]


Q42. Subtract 5 from every element.

In [65]:
print(c-10)

[ 90 190 290 390]


Q43. Find total sales.

In [66]:
print(np.sum(c))

1000


Q44. Find average sales.

In [67]:
print(np.average(c))

250.0


Q45. Find maximum sales.

In [68]:
print(np.max(c))

400


Q46. Find minimum sales.

In [69]:
print(np.min(c))

100


Q47. Find standard deviation.

In [70]:
print(np.std(c))

111.80339887498948


Q48. Find variance.

In [71]:
print(np.var(c))

12500.0


Q49. Find median.

In [72]:
print(np.median(c))

250.0


Q50. Mini Project: Analyze a sales dataset using NumPy.

In [73]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])

data.shape

(1000, 10)

In [74]:
data

array([[ 1001,    52,     2, ...,     2, 18737,     2],
       [ 1002,    93,    15, ...,     4, 12728,     2],
       [ 1003,    15,     8, ...,     1, 16726,     2],
       ...,
       [ 1998,    18,    11, ...,     3, 18505,     4],
       [ 1999,   100,     1, ...,     3, 10564,     1],
       [ 2000,    86,     7, ...,     5, 19793,     3]], shape=(1000, 10))

Q1. Dataset Exploration

Find:

Shape
Number of Dimensions
Datatype
Total Number of Elements

In [75]:
print(data.dtype)
print(data.shape)
print(data.ndim)
print(data.size)


int64
(1000, 10)
2
10000


Q2. First Look at Data

Display:

First 10 rows

Last 10 rows

In [76]:
print(data[0:11,0:11])
print(data[990:1001,0:11])

[[ 1001    52     2  1724     7 30461 12566     2 18737     2]
 [ 1002    93    15  2872    19 13102  2359     4 12728     2]
 [ 1003    15     8  3826    16  9756 10120     1 16726     2]
 [ 1004    72     8  3247     0 21084  1357     5 17481     2]
 [ 1005    61    17  4189    11 47480   564     3 16430     4]
 [ 1006    21    12  4906    25 35181 14162     1 13114     5]
 [ 1007    83    19  2290    18 26292  3394     3 10616     4]
 [ 1008    87    10  1016    14 22404  6874     5 13644     4]
 [ 1009    75     9  4086     8 43861  7531     4 16413     1]
 [ 1010    75     5  2975     6 35040  1330     2 11203     1]
 [ 1011    88     6  1540     1 27036 10946     2 19951     1]]
[[ 1991    17     6  3860     3 22750  2562     5 19344     5]
 [ 1992    13     2  1975     0 19450 13750     5 16985     3]
 [ 1993    84    18  4133    17 17859  9922     2 10947     3]
 [ 1994    25    13  1089     0 24096 13592     2 14760     4]
 [ 1995    68     9  3844    25 26030   387     1 1990

Q3. Using the Sales column:(Sales Column number 5)

Find:

Total Sales

Average Sales

Maximum Sales

Minimum Sales

In [77]:
print(np.sum(data[:,5]))
print(np.average(data[:,5]))
print(np.max(data[:,5]))
print(np.min(data[:,5]))

25288432
25288.432
49930
582


Q4. Using the Profit column:(column number 6)

Find:

Total Profit

Average Profit

Maximum Profit

In [78]:
print(np.sum(data[:,6]))
print(np.average(data[:,6]))
print(np.max(data[:,6]))


7557939
7557.939
14984


Q5. Indexing Challenge

Display:

Row 100

Row 500

Row 999

In [79]:
print(data[100,:])
print(data[500,:])
print(data[999,:])

[ 1101    26     5  4776     1 13656  3418     4 11716     3]
[ 1501    76     4  1137    13 48463 13126     1 17054     5]
[ 2000    86     7  2559    22 30268   229     5 19793     3]


Q6. Slicing Challenge

Display:

Rows 100–200

First 5 columns

Last 3 columns

In [80]:
print(data[100:201,:])
print(data[:,0:6])
print(data[:,7:11])

[[ 1101    26     5 ...     4 11716     3]
 [ 1102    89    19 ...     1 10786     1]
 [ 1103    60    14 ...     1 14368     1]
 ...
 [ 1199    72     8 ...     4 11410     3]
 [ 1200    27     9 ...     2 10534     5]
 [ 1201     9    11 ...     2 19908     4]]
[[ 1001    52     2  1724     7 30461]
 [ 1002    93    15  2872    19 13102]
 [ 1003    15     8  3826    16  9756]
 ...
 [ 1998    18    11   693    19 23115]
 [ 1999   100     1  1874    19  3827]
 [ 2000    86     7  2559    22 30268]]
[[    2 18737     2]
 [    4 12728     2]
 [    1 16726     2]
 ...
 [    3 18505     4]
 [    3 10564     1]
 [    5 19793     3]]


Q7. Advanced Slicing

Display:

Every alternate row

Every alternate column

Dataset in reverse order

In [81]:
print(data[0:1001:2,:])
print(data[:,0:11:2])
print(data[::-1,::-1])

[[ 1001    52     2 ...     2 18737     2]
 [ 1003    15     8 ...     1 16726     2]
 [ 1005    61    17 ...     3 16430     4]
 ...
 [ 1995    68     9 ...     1 19909     2]
 [ 1997    67    13 ...     2 18828     4]
 [ 1999   100     1 ...     3 10564     1]]
[[ 1001     2     7 12566 18737]
 [ 1002    15    19  2359 12728]
 [ 1003     8    16 10120 16726]
 ...
 [ 1998    11    19  2007 18505]
 [ 1999     1    19  1261 10564]
 [ 2000     7    22   229 19793]]
[[    3 19793     5 ...     7    86  2000]
 [    1 10564     3 ...     1   100  1999]
 [    4 18505     3 ...    11    18  1998]
 ...
 [    2 16726     1 ...     8    15  1003]
 [    2 12728     4 ...    15    93  1002]
 [    2 18737     2 ...     2    52  1001]]


Q8. Broadcasting

Management decides to increase all sales by 10%.

Create a new sales array with updated values.

In [82]:
d=data[:,5]
print(d)
print()
print(d*1.1)

[30461 13102  9756 21084 47480 35181 26292 22404 43861 35040 27036 19664
 13496  3371 46502 23126 11021 43910  1632 33967 15034 24354 43498 39565
 46107  8312  5057  2679 44298  9565  8775 48357 36448 21200 39964 42851
 28294 29283 17498 14369 45025 28652 21454 32055 17154 45526 35736 47476
 15542 26466 48907 44814 45595 14770 31408 16023 47568 20491 11275 12765
 19959 17173 27556  7114 36520  7915 23655 49930 44384 17464 38226 37544
 38044 32752  4332 25775 15401 38713 34648 43133 23418 47194 20040 12080
 38902 39078 25417 22818 10679 12751 46399 19993 20966 30706 45975 20124
 27064 22912 28490 36017 13656 23564 26211 30606 17089 24236 21475 36718
  7714 31081 20695 45082 27627  5641 29384 25385  3208 18875 15588 45102
 45546 10514  3773 47635 37806 31381 31986 13041  9212  9668  4051 12797
 44233 27628  3332 28983 22563 23463 13922 33420 11656 11608 32345  3300
 38578 43212  3110 12567 34372 11228 30066 30283 21083 20738  7763  2414
 24249 19956 26082   906 14189 33434 33776 36932 20

Q9. Business Filtering

Find:

Number of orders where Sales > ₹25,000

Number of orders where Profit > ₹5,000

In [83]:
print(d[d[:]>25000].size)
print(data[data[:,6]>5000].size)

509
6580


Q10. Management Report

Create a final report showing:

Total Sales

Average Sales

Total Profit

Average Profit

Highest Sale

Highest Profit

Number of High-Value Orders (Sales > ₹25,000)

In [84]:
print(np.sum(data[:,5]))
print(np.average(data[:,5]))
print(np.sum(data[:,6]))
print(np.average(data[:,6]))
print(max(data[:,5]))
print(min(data[:,6]))

25288432
25288.432
7557939
7557.939
49930
116
